name: octodb_sqflite_common
homepage: https://github.com/octodb/sqflite/tree/master/sqflite_common
description: Dart wrapper on OctoDB & SQLite
version: 2.0.0-dev.1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  synchronized: '>=3.0.0 <5.0.0'
  path: '>=1.8.0-0 <3.0.0'
  meta: '>=1.3.0 <3.0.0'

dev_dependencies:
  pedantic: '>=1.10.0'
  process_run: '>=0.12.0'
  http: '>=0.13.0'
  test: '>=1.16.2'
  test_api: '>=0.2.19'
  pub_semver: '>=2.0.0'
