name: octodb_sqflite
homepage: https://github.com/octodb/sqflite/tree/master/sqflite
description: Flutter plugin for OctoDB and SQLite
version: 2.0.0-dev.1

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.10.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.tekartik.sqflite
        pluginClass: SqflitePlugin
      ios:
        pluginClass: SqflitePlugin
      macos:
        pluginClass: SqflitePlugin

dependencies:
  flutter:
    sdk: flutter
  octodb_sqflite_common: '>=2.0.0 <4.0.0'
  path: '>=1.8.0-0 <3.0.0'

dev_dependencies:
  pedantic: '>=1.10.0'
  process_run: '>=0.12.0'
  http: '>=0.13.0'
  flutter_test:
    sdk: flutter
  test_api: '>=0.2.19'
  pub_semver: '>=2.0.0'
